name: Trigger GAM with GH CLI

on:
  workflow_dispatch: {}

env:
  COMPONENT: "Dashboard"

jobs:
  trigger-gam:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/create-github-app-token@v1
      id: app-token
      with:
        app-id: ${{ secrets.APP_ID }}
        private-key: ${{ secrets.PRIVATE_KEY }}
        owner: red-hat-data-services
        repositories: gam-poc

    - name: Get GitHub App User ID
      id: get-user-id
      run: echo "user-id=$(gh api "/users/${{ steps.app-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
      env:
        GH_TOKEN: ${{ steps.app-token.outputs.token }}

    - name: configure git committer string
      run: |
        git config --global user.name '${{ env.COMPONENT }}'


    - name: Trigger GAM
      env:
        GH_TOKEN: ${{ steps.app-token.outputs.token }}
      run: |
        gh workflow run test.yaml --repo red-hat-data-services/gam-poc \
                  --ref main \
                  --field component=${{ env.COMPONENT }} \
                  --field workflow_run_id=${GITHUB_RUN_ID}

    - name: Fetch GAM Trigger Workflow details
      env:
        GH_TOKEN: ${{ steps.app-token.outputs.token }}
      run: |
        sleep 5  # Wait for 5 seconds
        
        # Fetch the triggered workflow details
        workflow_details=$(gh run list --repo red-hat-data-services/gam-poc \
                             --workflow 127286462 \
                             --json name,databaseId,url,workflowDatabaseId,workflowName,conclusion,createdAt,displayTitle,status \
                             --jq 'map(select(.name | contains("${{ env.COMPONENT }}-${GITHUB_RUN_ID}")))')
                             
        # Print the output to the screen
        echo "Workflow details: $(echo "$workflow_details" | jq '.')"
    
        # Exit if more than one workflow detail exists
        if [ $(echo "$workflow_details" | jq 'length') -gt 1 ]; then
          echo "Error: More than one workflow detail found." && exit 1
        fi

        # Extract first object and convert it to a compact string
        workflow_run_id=$(echo "$workflow_details" | jq '.[0].databaseId')
        workflow_run_name=$(echo "$workflow_details" | jq '.[0].name')
        workflow_run_url=$(echo "$workflow_details" | jq '.[0].url')
    
        # Save the output as GitHub Actions Env Variables
        echo "workflow_run_id=$workflow_run_id" >> $GITHUB_ENV
        echo "workflow_run_name=$workflow_run_name" >> $GITHUB_ENV
        echo "workflow_run_url=$workflow_run_url" >> $GITHUB_ENV
    
    - name: Watch Workflow Logs
      env:
        GH_TOKEN: ${{ steps.app-token.outputs.token }}
      run: |
        gh run watch --repo red-hat-data-services/gam-poc ${{ env.workflow_run_id }}

        echo ""
        echo "Workflow Name: ${{ env.workflow_run_name }}"
        echo "To watch full logs, click ${{ env.workflow_run_url }}"
